[package]
name = "multi-log-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
big-int = "7.0.0"
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
num-bigint = "0.4.6"
regex = "1.11.1"
